### ISSUE TITLE
CANNOT ACCESS DASHBOARD

### ISSUE THREAD

**Issue by peterburr** [ircwash/WASHCost-tool#32] opened 2014-06-17 08:54 UTC
I am getting an error message of "we are sorry, but something went wrong" when I try to access my dashboard for the account linked to email burr@ircwash.org

I have another profile linked to peteburr@gmail.com and that is working fine.

**Comment by mhig** [comment] 2014-06-18 08:38
Hi Peter - we need more information about the circumstance that led to this so that we can resolve it. What did you do before, have you managed to repeat it?

**Comment by nickdickinson** [comment] 2014-06-18 08:47
I can confirm this was because of a report I created with the API. After
creation, the dashboard always stops working.

_From:_ mhig [mailto:notifications@github.com]
_Sent:_ 18 June 2014 10:39
_To:_ ircwash/WASHCost-tool
_Subject:_ Re: [WASHCost-tool] CANNOT ACCESS DASHBOARD (#32)

Hi Peter - we need more information about the circumstance that led to this
so that we can resolve it. What did you do before, have you managed to
repeat it?

—
Reply to this email directly or view it on GitHub
https://github.com/ircwash/WASHCost-tool/issues/32#issuecomment-46409632.[image:
Image removed by sender.]

## 

http://www.irc.nl/page/73684

**Comment by mhig** [comment] 2014-06-18 08:48
Merged with #31

**Closed as completed by mhig** 2014-06-18 08:48 UTC
